[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
web3 = "0.19"
rdkafka = { version = "0.29", features = ["tokio"] }
