[package]
name = "sto_listener"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
web3 = "0.19.0"
rdkafka = { version = "0.29", features = ["tokio"] }
serde_json = "1.0"
ethereum-types = "0.14"
ethabi = "18.0"
