[package]
name = "sto_listener"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
web3 = "0.19.0"
rdkafka = { version = "0.29", features = ["tokio"] }
